# Numpy 

In [ ]:
# import numpy library
import numpy as np

In [4]:
my_list= [1,2,3,4,5]

In [6]:
arr= np.array(my_list)

In [8]:
arr[3]

4

In [9]:
v= np.array([1,2,3])

In [10]:
v

array([1, 2, 3])

In [11]:
v1= np.array([[1],[2],[3]])

In [12]:
v1

array([[1],
       [2],
       [3]])

In [13]:
v.ndim

1

In [14]:
v1.ndim

2

### Matrix

In [23]:
matrix= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
matrix.ndim

2

In [26]:
matrix.shape

(3, 3)

In [27]:
matrix[1,1]

5

In [30]:
matrix[ :3 , 1:2 ]

array([[2],
       [5],
       [8]])

In [31]:
matrix.size

9

In [32]:
np.max(matrix)

9

In [33]:
np.min(matrix)

1

In [36]:
np.max(matrix, axis=1)

array([3, 6, 9])

In [38]:
matrix.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])